---
title: "hpai-manuscript-bird-abd-analysis"
author: "Rishi Kowalski, ScM"
date: "2026-01-17"
output: html_document
---

Bird Abundance Data Manipulation and WQS Analaysis for Manuscript Submission
Created 1/16/26 by rishi.kowalski@mssm.edu

```{r setup-dependencies}
library(terra)
library(ebirdst)
library(dplyr)
library(sf)
library(gWQS)
library(lwqs)
library(tidyr)
library(ggplot2)
library(geosphere)
library(RColorBrewer)
library(cowplot)
library(parallel)
library(MMWRweek)
library(gridExtra)
library(grid)
```

```{r setup-raster-list}
#Bird Top 15 Anseriforms in MN
#Initialize list of rasters - 15 anseriformes and 10 non-anseriform HPAI detections
#Top 15 Anseriforms identified in MN via iNaturalist List: https://www.inaturalist.org/guides/14807?taxon=6888
mn_anseri_15 <- c("mallar3", "cangoo", "wooduc", "buwtea", "commer", "rinduc", "comgol", "norsho", "buffle", "lessca", "rebmer", "gnwtea", "gadwal", "ambduc", "rudduc")


##### Abundance #####
#Anseriforms, n = 15
mallar3_abd_3km <- load_raster("mallar3" , product = "abundance", resolution = "3km")
cangoo_abd_3km <- load_raster("cangoo", product = "abundance", resolution = "3km")
wooduc_abd_3km <- load_raster("wooduc", product = "abundance", resolution = "3km")
buwtea_abd_3km <- load_raster("buwtea", product = "abundance", resolution = "3km")
commer_abd_3km <- load_raster("commer", product = "abundance", resolution = "3km")
rinduc_abd_3km <- load_raster("rinduc", product = "abundance", resolution = "3km")
comgol_abd_3km <- load_raster("comgol", product = "abundance", resolution = "3km")
norsho_abd_3km <- load_raster("norsho", product = "abundance", resolution = "3km")
buffle_abd_3km <- load_raster("buffle", product = "abundance", resolution = "3km")
lessca_abd_3km <- load_raster("lessca", product = "abundance", resolution = "3km")
rebmer_abd_3km <- load_raster("rebmer", product = "abundance", resolution = "3km")
gnwtea_abd_3km <- load_raster("gnwtea", product = "abundance", resolution = "3km")
gadwal_abd_3km <- load_raster("gadwal", product = "abundance", resolution = "3km")
ambduc_abd_3km <- load_raster("ambduc", product = "abundance", resolution = "3km")
rudduc_abd_3km <- load_raster("rudduc", product = "abundance", resolution = "3km")

#Non-Anseriform HPAI Detections, n = 6
rethaw_abd_3km <- load_raster("rethaw", product = "abundance", resolution = "3km")
truswa_abd_3km <- load_raster("truswa", product = "abundance", resolution = "3km")
grhowl_abd_3km <- load_raster("grhowl", product = "abundance", resolution = "3km")
amwpel_abd_3km <- load_raster("amwpel", product = "abundance", resolution = "3km")
baleag_abd_3km <- load_raster("baleag", product = "abundance", resolution = "3km")
brdowl_abd_3km <- load_raster("brdowl", product = "abundance", resolution = "3km")

spec_rast_list <- list(mallar3_abd_3km, cangoo_abd_3km, wooduc_abd_3km, buwtea_abd_3km, commer_abd_3km, rinduc_abd_3km, comgol_abd_3km, norsho_abd_3km, buffle_abd_3km, lessca_abd_3km, rebmer_abd_3km, gnwtea_abd_3km, gadwal_abd_3km, ambduc_abd_3km, rudduc_abd_3km, rethaw_abd_3km, truswa_abd_3km, grhowl_abd_3km, amwpel_abd_3km, baleag_abd_3km, brdowl_abd_3km)


names(spec_rast_list) <- c("mallar3", "cangoo", "wooduc", "buwtea", "commer", "rinduc", "comgol", "norsho", "buffle", "lessca", "rebmer", "gnwtea", "gadwal", "ambduc", "rudduc", "rethaw", "truswa", "grhowl", "amwpel", "baleag", "brdowl")

# Dataset for names
spec_name_com <- ebirdst_runs[ebirdst_runs$species_code %in% names(spec_rast_list), c("species_code", "common_name")]
spec_name_com$spec_source <- ifelse(spec_name_com$species_code %in% mn_anseri_15, "common-anseriform", "2022-hpai-detects")
```

### Re-pull Data ###

- Version: 01/29/26: use date_confirmed
-Repull, initally for MN, then all US outbreaks (maybe in Minerva)
-01/16/26

```{r pull-outbreak-level-data}
hpai_outbreak_all <- read.csv("//Users/kowalr03/Data/hpai/hpai-outbreaks-clean-placeholder-032124.csv")

# Get MMWR week of each outbreak by date_analyzed
# If NA use date_confirmed
outbreak_id_week <- hpai_outbreak_all %>% 
                      distinct(outbreak_id, date_analyzed, date_confirmed) %>% 
                      mutate(
                        outbreak_date = ifelse(is.na(date_confirmed), date_analyzed, date_confirmed),
                        outbreak_week = MMWRweek(as.Date(outbreak_date))$MMWRweek,
                        week_outbreak = 1) # for join later

hpai_outbreak_mn <- subset(hpai_outbreak_all, state == "MN")

#hpai_outbreak_mn_pt <- vect(hpai_outbreak_mn[, c("lat", "lon")], crs = "+proj=longlat")
hpai_outbreak_pt <- vect(hpai_outbreak_all[, c("lat", "lon")], crs = "+proj=longlat")

#hpai_outbreak_mn_pt_buf <- buffer(hpai_outbreak_mn_pt, 3000)
hpai_outbreak_us_pt_buf <- buffer(hpai_outbreak_pt, 3000)

# convert to ebird crs
#hpai_outbreak_mn_pts_buf_prj <- project(hpai_outbreak_mn_pt_buf, spec_rast_list[[1]])
hpai_outbreak_pts_buf_prj <- project(hpai_outbreak_us_pt_buf, spec_rast_list[[1]])

# extract all species, mean and sum
#extr_lst_sum <- mclapply(spec_rast_list, function(x) terra::extract(x, hpai_outbreak_mn_pts_buf_prj, fun = "sum", touches = T, na.rm = T), mc.cores = 5)
#extr_lst_avg <- mclapply(spec_rast_list, function(x) terra::extract(x, hpai_outbreak_mn_pts_buf_prj, fun = "mean", touches = T, na.rm = T), mc.cores = 5)

extr_lst_sum <- mclapply(spec_rast_list, function(x) terra::extract(x, hpai_outbreak_pts_buf_prj, fun = sum, touches = T, na.rm = T), mc.cores = 5)
extr_lst_avg <- mclapply(spec_rast_list, function(x) terra::extract(x, hpai_outbreak_pts_buf_prj, fun = mean, touches = T, na.rm = T), mc.cores = 5)

# structure
strFunction <- function(index_get) {
  extr_df_sum <- extr_lst_sum[[index_get]]
  extr_df_avg <- extr_lst_avg[[index_get]]
  
  extr_df_sum$outbreak_id <- hpai_outbreak_all$outbreak_id
  extr_df_avg$outbreak_id <- hpai_outbreak_all$outbreak_id
  
  extr_df_sum_lng <- tidyr::pivot_longer(extr_df_sum %>% select(-ID), cols = -outbreak_id, names_to = "week", values_to = "abd_sum")
  extr_df_avg_lng <- tidyr::pivot_longer(extr_df_avg %>% select(-ID), cols = -outbreak_id, names_to = "week", values_to = "abd_avg")
  
  spec_df_lng <- left_join(extr_df_sum_lng, extr_df_avg_lng, by = c("outbreak_id", "week"))
  spec_df_lng$species_name <- names(spec_rast_list)[index_get]
  
  spec_df_lng <- spec_df_lng[, c("outbreak_id", "species_name", "week", "abd_sum", "abd_avg")] # reorder
  
  return(spec_df_lng)
}

#all_mn_ob_abd <- do.call("rbind", lapply(1:length(extr_lst_avg), strFunction))
#all_mn_ob_abd$week <- MMWRweek(as.Date(all_mn_ob_abd$week)$week)

all_us_ob_abd <- do.call("rbind", lapply(1:length(extr_lst_avg), strFunction))
all_us_ob_abd$mmwr_week <- MMWRweek(as.Date(all_us_ob_abd$week))$MMWRweek

all_us_ob_abd_out <- left_join(all_us_ob_abd, outbreak_id_week %>% select(outbreak_id, outbreak_week, week_outbreak),
                           by = c("outbreak_id", "mmwr_week" = "outbreak_week")) %>%
                      mutate(week_outbreak = ifelse(is.na(week_outbreak), 0, week_outbreak))

#write.csv(all_us_ob_abd_out, "//Users/kowalr03/OneDrive - The Mount Sinai Hospital/HPAI_data/hpai-data-sharing/hpai-manuscript-update/usa-outbreak-weekly-bird-estimate-2022-012926.csv", row.names = F)

#write.csv(all_us_ob_abd_out %>% filter(outbreak_id %in% hpai_outbreak_mn$outbreak_id), "//Users/kowalr03/OneDrive - The Mount Sinai Hospital/HPAI_data/hpai-data-sharing/hpai-manuscript-update/mn-outbreak-weekly-bird-estimate-2022-012926.csv", row.names = F)

##### Verification of Points Etc #####
#mn_shape <- vect("//Users/kowalr03/Data/utils/shapefiles/cb_2017_us_state_27_500k/cb_2017_us_state_27_500k.shp", crs = "EPSG:3857")
#mn_shape_prj <- project(mn_shape, hpai_outbreak_mn_pt)
```

### Run New WQS ###

```{r run-wqs}
##### Data #####
all_mn_abd <- read.csv("//Users/kowalr03/OneDrive - The Mount Sinai Hospital/HPAI_data/hpai-data-sharing/hpai-manuscript-update/mn-outbreak-weekly-bird-estimate-2022-012926.csv")

# Construct case + controls
# -> controls = case + 4 -- case + 8 per FM correspondance 1/20
ob_week <- all_mn_abd %>% 
  filter(week_outbreak == 1) %>% 
  distinct(outbreak_id, mmwr_week) %>%
  mutate(
    season_outbreak = case_when(
                        mmwr_week %in% c(1:9, 48:52) ~ "winter",
                        mmwr_week %in% 10:22 ~ "spring",
                        mmwr_week %in% 23:35 ~ "summer",
                        mmwr_week %in% 36:47 ~ "fall",
                        TRUE ~ NA))


# Case-control here: 4 week preceding week of outbreak, 4 weeks 4 weeks post outbreak, week of outbreak inclusive
ob_week_per_4 <- purrr::map2(ob_week$outbreak_id, ob_week$mmwr_week, function(id, week) 
  data.frame(outbreak_id = rep(id, 10), 
             mmwr_week = c(seq(week-4, week, 1), seq(week+4, week+8, 1)),
             study_period = rep(c("case-period", "ctrl-period"), each = 5))) %>%
  bind_rows()

# 3 week preceding week of outbreak, 3 weeks 4 weeks post outbreak, week of outbreak inclusive
ob_week_per_3 <- purrr::map2(ob_week$outbreak_id, ob_week$mmwr_week, function(id, week) 
  data.frame(outbreak_id = rep(id, 8), 
             mmwr_week = c(seq(week-3, week, 1), seq(week+4, week+7, 1)),
             study_period = rep(c("case-period", "ctrl-period"), each = 4))) %>%
  bind_rows()

# Join periods to data
hpai_outbreak_mn_case_ctrl_lag4 <- left_join(all_mn_abd, ob_week_per_4, by = c("outbreak_id", "mmwr_week"))
hpai_outbreak_mn_case_ctrl_lag3 <- left_join(all_mn_abd, ob_week_per_3, by = c("outbreak_id", "mmwr_week"))

# Get common species name
hpai_outbreak_mn_case_ctrl_lag4 <- left_join(hpai_outbreak_mn_case_ctrl_lag4, spec_name_com %>% select(species_code, common_name), by = c("species_name" = "species_code"))
hpai_outbreak_mn_case_ctrl_lag3 <- left_join(hpai_outbreak_mn_case_ctrl_lag3, spec_name_com %>% select(species_code, common_name), by = c("species_name" = "species_code"))

# Aggregate by case and control period
mn_hpai_abd_pt_cumul_lag4 <- hpai_outbreak_mn_case_ctrl_lag4 %>% 
                                filter(!is.na(study_period)) %>%
                                group_by(outbreak_id, study_period, common_name) %>%
                                summarise(
                                  sum_abd = sum(abd_sum)) %>%
                                ungroup() %>%
                                pivot_wider(., id_cols = c("outbreak_id", "study_period"), names_from = common_name,  values_from = sum_abd) %>%
                                mutate(outbreak_status = ifelse(study_period == "case-period", 1, 0)) %>%
                                relocate(outbreak_status, .after = study_period)

# Aggregate by case and control week
mn_hpai_abd_pt_cumul_lag3 <- hpai_outbreak_mn_case_ctrl_lag3 %>% 
                                filter(!is.na(study_period)) %>%
                                group_by(outbreak_id, study_period, common_name) %>%
                                summarise(
                                  sum_abd = sum(abd_sum)) %>%
                                ungroup() %>%
                                pivot_wider(., id_cols = c("outbreak_id", "study_period"), names_from = common_name,  values_from = sum_abd) %>%
                                mutate(outbreak_status = ifelse(study_period == "case-period", 1, 0)) %>%
                                relocate(outbreak_status, .after = study_period)

# Join season to outbreak dataset
mn_hpai_abd_pt_cumul_lag4 <- left_join(mn_hpai_abd_pt_cumul_lag4, ob_week %>% select(outbreak_id, season_outbreak), by = "outbreak_id")  %>%
                                relocate(season_outbreak, .after = outbreak_id)

mn_hpai_abd_pt_cumul_lag3 <- left_join(mn_hpai_abd_pt_cumul_lag3, ob_week %>% select(outbreak_id, season_outbreak), by = "outbreak_id") %>%
                              relocate(season_outbreak, .after = outbreak_id)

#write.csv(mn_hpai_abd_pt_cumul_lag4, "//Users/kowalr03/OneDrive - The Mount Sinai Hospital/HPAI_data/hpai-data-sharing/hpai-manuscript-update/wqs-modeling-update/mn-hpai-cumulative-lag-case-lag4-control-012926.csv", row.names = F)
#write.csv(mn_hpai_abd_pt_cumul_lag3, "//Users/kowalr03/OneDrive - The Mount Sinai Hospital/HPAI_data/hpai-data-sharing/hpai-manuscript-update/wqs-modeling-update/mn-hpai-cumulative-lag-case-lag3-control-012926.csv", row.names = F)
```



```{r wqs-modeling}
library(gWQS)
library(dplyr)

mn_hpai_abd_pt_cumul_lag4 <- read.csv("//Users/kowalr03/OneDrive - The Mount Sinai Hospital/HPAI_data/hpai-data-sharing/hpai-manuscript-update/wqs-modeling-update/mn-hpai-cumulative-lag-case-lag4-control-012926.csv")
mn_hpai_abd_pt_cumul_lag3 <- read.csv("//Users/kowalr03/OneDrive - The Mount Sinai Hospital/HPAI_data/hpai-data-sharing/hpai-manuscript-update/wqs-modeling-update/mn-hpai-cumulative-lag-case-lag3-control-012926.csv")

# 0-quantiling per CJ suggestion
zeroQuantVar <- function(bird_col) {
  bird_qt <- ifelse(bird_col <= 0, NA, bird_col)
  qtile <- quantile(bird_qt, na.rm = T)
  col_qtile <- cut(bird_qt, breaks = qtile, include.lowest = T)
  col_qtile <- ifelse(is.na(col_qtile), 0, col_qtile)  
  return(col_qtile)
}



# WQS - lag4
vars_out <- c("outbreak_id", "season_outbreak", "study_period", "outbreak_status", "American.Black.Duck")
spec_mix_mod_l4 <- names(mn_hpai_abd_pt_cumul_lag4)[!names(mn_hpai_abd_pt_cumul_lag4) %in% vars_out]

mn_hpai_abd_pt_cumul_lag4_zq <- mn_hpai_abd_pt_cumul_lag4 %>% 
                                  filter(season_outbreak %in% c("spring", "fall")) %>% # remove n = 6 winter/summer outbreaks
                                  mutate(across(all_of(spec_mix_mod_l4), zeroQuantVar))

system.time(
  wqs_4_lag_cumul <- gwqs(outbreak_status ~ wqs + season_outbreak, 
                          mix_name = spec_mix_mod_l4, data = mn_hpai_abd_pt_cumul_lag4_zq, 
                          q = NULL, validation = 0.6, b = 50, b1_pos = T, rh = 100, family = "binomial", seed = 1)
)

# WQS - lag3
# Zero-quantiling does not work for American Black Duck, so remove from analysis
vars_out <- c("outbreak_id", "season_outbreak", "study_period", "outbreak_status", "American.Black.Duck")
spec_mix_mod_l3 <- names(mn_hpai_abd_pt_cumul_lag3)[!names(mn_hpai_abd_pt_cumul_lag3) %in% vars_out]

mn_hpai_abd_pt_cumul_lag3_zq <- mn_hpai_abd_pt_cumul_lag3 %>% 
                                  filter(season_outbreak %in% c("spring", "fall")) %>% # remove n = 6 winter/summer outbreaks
                                  mutate(across(all_of(spec_mix_mod_l3), zeroQuantVar))

system.time(
  wqs_3_lag_cumul <- gwqs(outbreak_status ~ wqs + season_outbreak, 
                          mix_name = spec_mix_mod_l3, data = mn_hpai_abd_pt_cumul_lag3_zq, 
                          q = NULL, validation = 0.6, b = 50, b1_pos = T, rh = 100, family = "binomial", seed = 1)
)

# Plots
bar_lag4 <- gwqs_barplot(wqs_4_lag_cumul) + labs(title = "Cumulative Lag = 4") + scale_y_continuous(breaks = seq(0, .15, .05), limits = c(0, .165), expand = c(0,0)) + theme(title = element_text(size = 8)) 
bar_lag3 <- gwqs_barplot(wqs_3_lag_cumul) + labs(title = "Cumulative Lag = 3") + scale_y_continuous(breaks = seq(0, .15, .05), limits = c(0, .165), expand = c(0,0)) + theme(title = element_text(size = 8))

box_lag4 <- gwqs_boxplot(wqs_4_lag_cumul) + labs(title = "Species Case-Control WQS, Cumulative Lag = 4", x = "Species")
box_lag3 <- gwqs_boxplot(wqs_3_lag_cumul) + labs(title = "Species Case-Control WQS, Cumulative Lag = 3", x = "Species")


#ggsave("//Users/kowalr03/OneDrive - The Mount Sinai Hospital/HPAI_data/hpai-data-sharing/hpai-manuscript-update/wqs-modeling-update/mn-case-ctrl-bar-lag4-012926.png", bar_lag4)
#ggsave("//Users/kowalr03/OneDrive - The Mount Sinai Hospital/HPAI_data/hpai-data-sharing/hpai-manuscript-update/wqs-modeling-update/mn-case-ctrl-bar-lag3-012926.png", bar_lag3)

#ggsave("//Users/kowalr03/OneDrive - The Mount Sinai Hospital/HPAI_data/hpai-data-sharing/hpai-manuscript-update/wqs-modeling-update/mn-case-ctrl-box-lag4-012926.png", box_lag4)
#ggsave("//Users/kowalr03/OneDrive - The Mount Sinai Hospital/HPAI_data/hpai-data-sharing/hpai-manuscript-update/wqs-modeling-update/mn-case-ctrl-box-lag3-012926.png", box_lag3)

# Arrange bar plots into single plot

png("//Users/kowalr03/OneDrive - The Mount Sinai Hospital/HPAI_data/hpai-data-sharing/hpai-manuscript-update/wqs-modeling-update/mn-case-ctrl-bar-both-012926.png", width = 5.5, height = 7.5, units = "in", res = 300)
grid.arrange(bar_lag3, bar_lag4, ncol = 1, newpage = F, top = textGrob("Species WQS at Farm Location", gp = gpar(fontface = 2, fontsize = 12), hjust = .5, x = .5))
dev.off()
```



