---
title: "Univariate DLNM screen across all candidate exposures"
author: "Fintan Mooney"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r initiate}
rm(list = ls())
# 0a.Declare root directory, folder location and load essential stuff
project.folder = paste0(print(here::here()), '/')
source(paste0(project.folder, 'create_folder_structure.R'))
source(paste0(functions.folder, 'script_initiate.R'))
```

# 1. Load case-crossover dataset

```{r load}
case_crossover_df <- readRDS(paste0(objects_folder, "case_crossover_df.RDS"))
setDT(case_crossover_df)
```

# 2. Build crossbases (primary spec: argvar lin, arglag ns df=4 for met, strata weekly for bird)

```{r crossbasis-met}
cb_temperature <- crossbasis(
  as.matrix(case_crossover_df[, paste0("temperature_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "ns", df = 4)
)
cb_dewpoint <- crossbasis(
  as.matrix(case_crossover_df[, paste0("dewpoint_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "ns", df = 4)
)
cb_relative_humidity <- crossbasis(
  as.matrix(case_crossover_df[, paste0("relative_humidity_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "ns", df = 4)
)
cb_wind_speed <- crossbasis(
  as.matrix(case_crossover_df[, paste0("wind_speed_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "ns", df = 4)
)
cb_soil_moisture <- crossbasis(
  as.matrix(case_crossover_df[, paste0("soil_moisture_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "ns", df = 4)
)
cb_snow_density <- crossbasis(
  as.matrix(case_crossover_df[, paste0("snow_density_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "ns", df = 4)
)
cb_precipitation <- crossbasis(
  as.matrix(case_crossover_df[, paste0("precipitation_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "ns", df = 4)
)
cb_runoff <- crossbasis(
  as.matrix(case_crossover_df[, paste0("runoff_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "ns", df = 4)
)
cb_evapotranspiration <- crossbasis(
  as.matrix(case_crossover_df[, paste0("evapotranspiration_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "ns", df = 4)
)
cb_leaf_area_index <- crossbasis(
  as.matrix(case_crossover_df[, paste0("leaf_area_index_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "ns", df = 4)
)
cb_shortwave_radiation <- crossbasis(
  as.matrix(case_crossover_df[, paste0("shortwave_radiation_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "ns", df = 4)
)
cb_longwave_radiation <- crossbasis(
  as.matrix(case_crossover_df[, paste0("longwave_radiation_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "ns", df = 4)
)
cb_surface_pressure <- crossbasis(
  as.matrix(case_crossover_df[, paste0("surface_pressure_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "ns", df = 4)
)
```

```{r crossbasis-bird}
cb_total_bird_abundance <- crossbasis(
  as.matrix(case_crossover_df[, paste0("total_bird_abundance_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "strata", breaks = c(7, 14, 21))
)
cb_anseriformes <- crossbasis(
  as.matrix(case_crossover_df[, paste0("anseriformes_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "strata", breaks = c(7, 14, 21))
)
cb_predators <- crossbasis(
  as.matrix(case_crossover_df[, paste0("predators_Lag", 0:28), with = FALSE]),
  lag = c(0, 28), argvar = list(fun = "lin"), arglag = list(fun = "strata", breaks = c(7, 14, 21))
)
```

# 3. Fit univariate conditional logistic models

```{r fit}
m_temperature          <- clogit(outbreak_binary ~ cb_temperature          + strata(stratum_id), data = case_crossover_df)
m_dewpoint             <- clogit(outbreak_binary ~ cb_dewpoint             + strata(stratum_id), data = case_crossover_df)
m_relative_humidity    <- clogit(outbreak_binary ~ cb_relative_humidity    + strata(stratum_id), data = case_crossover_df)
m_wind_speed           <- clogit(outbreak_binary ~ cb_wind_speed           + strata(stratum_id), data = case_crossover_df)
m_soil_moisture        <- clogit(outbreak_binary ~ cb_soil_moisture        + strata(stratum_id), data = case_crossover_df)
m_snow_density         <- clogit(outbreak_binary ~ cb_snow_density         + strata(stratum_id), data = case_crossover_df)
m_precipitation        <- clogit(outbreak_binary ~ cb_precipitation        + strata(stratum_id), data = case_crossover_df)
m_runoff               <- clogit(outbreak_binary ~ cb_runoff               + strata(stratum_id), data = case_crossover_df)
m_evapotranspiration   <- clogit(outbreak_binary ~ cb_evapotranspiration   + strata(stratum_id), data = case_crossover_df)
m_leaf_area_index      <- clogit(outbreak_binary ~ cb_leaf_area_index      + strata(stratum_id), data = case_crossover_df)
m_shortwave_radiation  <- clogit(outbreak_binary ~ cb_shortwave_radiation  + strata(stratum_id), data = case_crossover_df)
m_longwave_radiation   <- clogit(outbreak_binary ~ cb_longwave_radiation   + strata(stratum_id), data = case_crossover_df)
m_surface_pressure     <- clogit(outbreak_binary ~ cb_surface_pressure     + strata(stratum_id), data = case_crossover_df)
m_total_bird_abundance <- clogit(outbreak_binary ~ cb_total_bird_abundance + strata(stratum_id), data = case_crossover_df)
m_anseriformes         <- clogit(outbreak_binary ~ cb_anseriformes         + strata(stratum_id), data = case_crossover_df)
m_predators            <- clogit(outbreak_binary ~ cb_predators            + strata(stratum_id), data = case_crossover_df)
```

# 4. Cumulative OR (per 0.5 SD, lag 0–28 d)

```{r extract}
cp_temperature          <- crosspred(cb_temperature,          m_temperature,          cen = 0, at = 0.5, cumul = TRUE)
cp_dewpoint             <- crosspred(cb_dewpoint,             m_dewpoint,             cen = 0, at = 0.5, cumul = TRUE)
cp_relative_humidity    <- crosspred(cb_relative_humidity,    m_relative_humidity,    cen = 0, at = 0.5, cumul = TRUE)
cp_wind_speed           <- crosspred(cb_wind_speed,           m_wind_speed,           cen = 0, at = 0.5, cumul = TRUE)
cp_soil_moisture        <- crosspred(cb_soil_moisture,        m_soil_moisture,        cen = 0, at = 0.5, cumul = TRUE)
cp_snow_density         <- crosspred(cb_snow_density,         m_snow_density,         cen = 0, at = 0.5, cumul = TRUE)
cp_precipitation        <- crosspred(cb_precipitation,        m_precipitation,        cen = 0, at = 0.5, cumul = TRUE)
cp_runoff               <- crosspred(cb_runoff,               m_runoff,               cen = 0, at = 0.5, cumul = TRUE)
cp_evapotranspiration   <- crosspred(cb_evapotranspiration,   m_evapotranspiration,   cen = 0, at = 0.5, cumul = TRUE)
cp_leaf_area_index      <- crosspred(cb_leaf_area_index,      m_leaf_area_index,      cen = 0, at = 0.5, cumul = TRUE)
cp_shortwave_radiation  <- crosspred(cb_shortwave_radiation,  m_shortwave_radiation,  cen = 0, at = 0.5, cumul = TRUE)
cp_longwave_radiation   <- crosspred(cb_longwave_radiation,   m_longwave_radiation,   cen = 0, at = 0.5, cumul = TRUE)
cp_surface_pressure     <- crosspred(cb_surface_pressure,     m_surface_pressure,     cen = 0, at = 0.5, cumul = TRUE)
cp_total_bird_abundance <- crosspred(cb_total_bird_abundance, m_total_bird_abundance, cen = 0, at = 0.5, cumul = TRUE)
cp_anseriformes         <- crosspred(cb_anseriformes,         m_anseriformes,         cen = 0, at = 0.5, cumul = TRUE)
cp_predators            <- crosspred(cb_predators,            m_predators,            cen = 0, at = 0.5, cumul = TRUE)

n_temperature          <- ncol(cp_temperature$cumRRfit)
n_dewpoint             <- ncol(cp_dewpoint$cumRRfit)
n_relative_humidity    <- ncol(cp_relative_humidity$cumRRfit)
n_wind_speed           <- ncol(cp_wind_speed$cumRRfit)
n_soil_moisture        <- ncol(cp_soil_moisture$cumRRfit)
n_snow_density         <- ncol(cp_snow_density$cumRRfit)
n_precipitation        <- ncol(cp_precipitation$cumRRfit)
n_runoff               <- ncol(cp_runoff$cumRRfit)
n_evapotranspiration   <- ncol(cp_evapotranspiration$cumRRfit)
n_leaf_area_index      <- ncol(cp_leaf_area_index$cumRRfit)
n_shortwave_radiation  <- ncol(cp_shortwave_radiation$cumRRfit)
n_longwave_radiation   <- ncol(cp_longwave_radiation$cumRRfit)
n_surface_pressure     <- ncol(cp_surface_pressure$cumRRfit)
n_total_bird_abundance <- ncol(cp_total_bird_abundance$cumRRfit)
n_anseriformes         <- ncol(cp_anseriformes$cumRRfit)
n_predators            <- ncol(cp_predators$cumRRfit)

univariate <- data.table(
  predictor = c("Temperature", "Dewpoint", "Relative Humidity", "Wind Speed",
                "Soil Moisture", "Snow Density", "Precipitation", "Runoff",
                "Evapotranspiration", "Leaf Area Index",
                "Shortwave Radiation", "Longwave Radiation", "Surface Pressure",
                "Total Bird Abundance", "Anseriformes", "Predators"),
  or  = c(cp_temperature$cumRRfit["0.5",          n_temperature],
          cp_dewpoint$cumRRfit["0.5",             n_dewpoint],
          cp_relative_humidity$cumRRfit["0.5",    n_relative_humidity],
          cp_wind_speed$cumRRfit["0.5",           n_wind_speed],
          cp_soil_moisture$cumRRfit["0.5",        n_soil_moisture],
          cp_snow_density$cumRRfit["0.5",         n_snow_density],
          cp_precipitation$cumRRfit["0.5",        n_precipitation],
          cp_runoff$cumRRfit["0.5",               n_runoff],
          cp_evapotranspiration$cumRRfit["0.5",   n_evapotranspiration],
          cp_leaf_area_index$cumRRfit["0.5",      n_leaf_area_index],
          cp_shortwave_radiation$cumRRfit["0.5",  n_shortwave_radiation],
          cp_longwave_radiation$cumRRfit["0.5",   n_longwave_radiation],
          cp_surface_pressure$cumRRfit["0.5",     n_surface_pressure],
          cp_total_bird_abundance$cumRRfit["0.5", n_total_bird_abundance],
          cp_anseriformes$cumRRfit["0.5",         n_anseriformes],
          cp_predators$cumRRfit["0.5",            n_predators]),
  lo  = c(cp_temperature$cumRRlow["0.5",          n_temperature],
          cp_dewpoint$cumRRlow["0.5",             n_dewpoint],
          cp_relative_humidity$cumRRlow["0.5",    n_relative_humidity],
          cp_wind_speed$cumRRlow["0.5",           n_wind_speed],
          cp_soil_moisture$cumRRlow["0.5",        n_soil_moisture],
          cp_snow_density$cumRRlow["0.5",         n_snow_density],
          cp_precipitation$cumRRlow["0.5",        n_precipitation],
          cp_runoff$cumRRlow["0.5",               n_runoff],
          cp_evapotranspiration$cumRRlow["0.5",   n_evapotranspiration],
          cp_leaf_area_index$cumRRlow["0.5",      n_leaf_area_index],
          cp_shortwave_radiation$cumRRlow["0.5",  n_shortwave_radiation],
          cp_longwave_radiation$cumRRlow["0.5",   n_longwave_radiation],
          cp_surface_pressure$cumRRlow["0.5",     n_surface_pressure],
          cp_total_bird_abundance$cumRRlow["0.5", n_total_bird_abundance],
          cp_anseriformes$cumRRlow["0.5",         n_anseriformes],
          cp_predators$cumRRlow["0.5",            n_predators]),
  hi  = c(cp_temperature$cumRRhigh["0.5",          n_temperature],
          cp_dewpoint$cumRRhigh["0.5",             n_dewpoint],
          cp_relative_humidity$cumRRhigh["0.5",    n_relative_humidity],
          cp_wind_speed$cumRRhigh["0.5",           n_wind_speed],
          cp_soil_moisture$cumRRhigh["0.5",        n_soil_moisture],
          cp_snow_density$cumRRhigh["0.5",         n_snow_density],
          cp_precipitation$cumRRhigh["0.5",        n_precipitation],
          cp_runoff$cumRRhigh["0.5",               n_runoff],
          cp_evapotranspiration$cumRRhigh["0.5",   n_evapotranspiration],
          cp_leaf_area_index$cumRRhigh["0.5",      n_leaf_area_index],
          cp_shortwave_radiation$cumRRhigh["0.5",  n_shortwave_radiation],
          cp_longwave_radiation$cumRRhigh["0.5",   n_longwave_radiation],
          cp_surface_pressure$cumRRhigh["0.5",     n_surface_pressure],
          cp_total_bird_abundance$cumRRhigh["0.5", n_total_bird_abundance],
          cp_anseriformes$cumRRhigh["0.5",         n_anseriformes],
          cp_predators$cumRRhigh["0.5",            n_predators])
)
univariate[, OR_CI := sprintf("%.2f (%.2f, %.2f)", or, lo, hi)]
univariate[, sig   := lo > 1 | hi < 1]
print(univariate[order(-or)])
```

# 5. Export comparison table

```{r table}
ft <- univariate[, .(predictor, OR_CI)] %>%
  flextable() %>%
  set_header_labels(predictor = "Predictor",
                    OR_CI     = "Cumulative OR (95% CI), lag 0–28 d") %>%
  fontsize(size = 11, part = "all") %>%
  autofit() %>%
  align(align = "center", part = "all") %>%
  theme_booktabs()

doc <- read_docx() %>%
  body_add_flextable(ft) %>%
  body_add_par(
    "Univariate cumulative odds ratios from time-stratified case-crossover DLNM, one variable per model, per 0.5 SD increase across lag 0-28 d. Strata: zone x year x calendar month x day-of-week.",
    style = "Normal"
  )
print(doc, target = paste0(tables_sensitivity_folder, "Table_Univariate_Screen.docx"))
```

# 6. Forest plot

```{r forest, fig.width = 8, fig.height = 8}
forest_df <- univariate[order(or)]
forest_df[, predictor := factor(predictor, levels = predictor)]

p_forest <- ggplot(forest_df, aes(x = or, y = predictor)) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "gray40") +
  geom_errorbarh(aes(xmin = lo, xmax = hi, color = sig), height = 0.25, linewidth = 0.6) +
  geom_point(aes(color = sig), size = 2.5) +
  scale_x_log10(breaks = c(0.1, 0.25, 0.5, 1, 2, 5, 10, 25)) +
  scale_color_manual(values = c("FALSE" = "gray35", "TRUE" = "firebrick"), guide = "none") +
  labs(x = "Cumulative OR (95% CI), per 0.5 SD, lag 0–28 d", y = NULL) +
  theme_minimal(base_size = 12) +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major.y = element_blank())

ggsave(paste0(figures_sensitivity_folder, "figure_univariate_screen.png"),
       p_forest, width = 8, height = 8, units = "in", dpi = 300)

print(p_forest)
```

# 7. Lag-response slices (all 16 predictors)

```{r slices, fig.width = 14, fig.height = 10}
png(paste0(figures_sensitivity_folder, "figure_univariate_slices.png"),
    width = 14, height = 10, units = "in", res = 300)

par(mfrow = c(4, 4), mar = c(4.0, 4.0, 2.5, 1), oma = c(3, 4, 0, 1),
    cex.main = 1.0, cex.lab = 0.95, cex.axis = 0.85)

plot(cp_temperature,          type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Temperature",          xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_dewpoint,             type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Dewpoint",             xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_relative_humidity,    type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Relative Humidity",    xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_wind_speed,           type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Wind Speed",           xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_soil_moisture,        type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Soil Moisture",        xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_snow_density,         type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Snow Density",         xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_precipitation,        type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Precipitation",        xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_runoff,               type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Runoff",               xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_evapotranspiration,   type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Evapotranspiration",   xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_leaf_area_index,      type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Leaf Area Index",      xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_shortwave_radiation,  type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Shortwave Radiation",  xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_longwave_radiation,   type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Longwave Radiation",   xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_surface_pressure,     type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Surface Pressure",     xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_total_bird_abundance, type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Total Bird Abundance", xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_anseriformes,         type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Anseriformes",         xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")
plot(cp_predators,            type = "slices", var = 0.5, ci = "area", col = "black", ci.arg = list(col = rgb(0,0,0,0.15), border = NA), lwd = 1.3, main = "Predators",            xlab = "", ylab = "", las = 1); abline(h = 1, lty = 2, col = "gray40")

mtext("Lag (days)",            side = 1, outer = TRUE, line = 0, cex = 1.0)
mtext("Odds Ratio (95% CI)",   side = 2, outer = TRUE, line = 0, cex = 1.0)
dev.off()
```

# 8. Weekly cumulative anchors per predictor

```{r weekly-cum}
weekly_cum <- function(cp, label) {
  fit <- cp$cumRRfit["0.5", ]; lo <- cp$cumRRlow["0.5", ]; hi <- cp$cumRRhigh["0.5", ]
  data.table(
    predictor = label,
    `Cum ≤ 0 d`  = sprintf("%.2f (%.2f, %.2f)", fit["lag0"],  lo["lag0"],  hi["lag0"]),
    `Cum ≤ 7 d`  = sprintf("%.2f (%.2f, %.2f)", fit["lag7"],  lo["lag7"],  hi["lag7"]),
    `Cum ≤ 14 d` = sprintf("%.2f (%.2f, %.2f)", fit["lag14"], lo["lag14"], hi["lag14"]),
    `Cum ≤ 21 d` = sprintf("%.2f (%.2f, %.2f)", fit["lag21"], lo["lag21"], hi["lag21"]),
    `Cum ≤ 28 d` = sprintf("%.2f (%.2f, %.2f)", fit["lag28"], lo["lag28"], hi["lag28"])
  )
}

weekly_tbl <- rbindlist(list(
  weekly_cum(cp_temperature,          "Temperature"),
  weekly_cum(cp_dewpoint,             "Dewpoint"),
  weekly_cum(cp_relative_humidity,    "Relative Humidity"),
  weekly_cum(cp_wind_speed,           "Wind Speed"),
  weekly_cum(cp_soil_moisture,        "Soil Moisture"),
  weekly_cum(cp_snow_density,         "Snow Density"),
  weekly_cum(cp_precipitation,        "Precipitation"),
  weekly_cum(cp_runoff,               "Runoff"),
  weekly_cum(cp_evapotranspiration,   "Evapotranspiration"),
  weekly_cum(cp_leaf_area_index,      "Leaf Area Index"),
  weekly_cum(cp_shortwave_radiation,  "Shortwave Radiation"),
  weekly_cum(cp_longwave_radiation,   "Longwave Radiation"),
  weekly_cum(cp_surface_pressure,     "Surface Pressure"),
  weekly_cum(cp_total_bird_abundance, "Total Bird Abundance"),
  weekly_cum(cp_anseriformes,         "Anseriformes"),
  weekly_cum(cp_predators,            "Predators")
))

ft_weekly <- weekly_tbl %>%
  flextable() %>%
  fontsize(size = 10, part = "all") %>%
  autofit() %>%
  align(align = "center", part = "all") %>%
  theme_booktabs()

doc <- read_docx() %>%
  body_add_flextable(ft_weekly) %>%
  body_add_par(
    "Cumulative odds ratios at weekly lag anchors from univariate case-crossover DLNMs, per 0.5 SD.",
    style = "Normal"
  )
print(doc, target = paste0(tables_sensitivity_folder, "Table_Univariate_Weekly.docx"))

print(weekly_tbl)
```

# 9. Export full results object

```{r save}
saveRDS(list(
  cumulative = univariate,
  weekly     = weekly_tbl,
  models     = list(
    temperature = m_temperature, dewpoint = m_dewpoint,
    relative_humidity = m_relative_humidity, wind_speed = m_wind_speed,
    soil_moisture = m_soil_moisture, snow_density = m_snow_density,
    precipitation = m_precipitation, runoff = m_runoff,
    evapotranspiration = m_evapotranspiration, leaf_area_index = m_leaf_area_index,
    shortwave_radiation = m_shortwave_radiation, longwave_radiation = m_longwave_radiation,
    surface_pressure = m_surface_pressure,
    total_bird_abundance = m_total_bird_abundance,
    anseriformes = m_anseriformes, predators = m_predators
  )
), paste0(objects_folder, "univariate_screen.RDS"))
```
